### PR TITLE
Add Rectangle test, test comparator

### PR DESCRIPTION
**Pull request by melisabok**
Add horizontalOverlap method
Add overlap tests

### CODE REVIEW

**Comment by melisabok** [comment]
Added some unit tests of Rectangle class.

@jazzido: this [test](https://github.com/melisabok/tabula-java/blob/feature/add-rectangle-tests/src/test/java/technology/tabula/TestRectangle.java#L147) check the horizontal overlapping between two rectangles and the ratio is zero, is it ok?

**Comment by jazzido** [comment]
> [...] check the horizontal overlapping between two rectangles and the ratio is zero, is it ok? 

Yes. `horizontalOverlapRatio` checks overlapping in the *vertical* direction.

**Comment by jazzido** [comment]
Thanks again!

**Comment by melisabok** [comment]
Ok, the thing is that the horizontalOverlap is > 0 but the horizontalOverlapRatio = 0. And I think that the ratio should be also > 0

```
		assertEquals(5f, one.horizontalOverlap(two), 0);
		assertEquals(0f, one.horizontalOverlapRatio(two), 0);
```

**Comment by jazzido** [comment]
There's definitely a naming bug. 

For instance, `horizontalOverlap` checks overlap in the X axis (using the `getRight` and `getLeft`), while `horizontalOverlapRatio` uses `getTop`, `getBottom`.

**Comment by melisabok** [comment]
So ```horizontalOverlapRatio``` should be renamed as ```verticalOverlapRatio```.  It's beeb called from [groupByLines](https://github.com/tabulapdf/tabula-java/blob/master/src/main/java/technology/tabula/TextChunk.java#L177) that makes sense to be 'vertical'.

**Comment by jazzido** [comment]
> So horizontalOverlapRatio should be renamed as verticalOverlapRatio
Exactly.

**Pull request merged**
