### PR TITLE
update pdfbox to 3.0.2

### PR DESCRIPTION
**Pull request by nanfangfanqie**

### CODE REVIEW

**Comment by jeremybmerrill** [comment]
Hi @nanfangfanqie : Thank you for this PR and I'm sorry that we didn't respond to it earlier. Upgrading to pdfbox 3 seems worthwhile.

However, I'm running into a bizarre problem: when I try to run the tests on your branch (with `mvn test`)... 0 tests get executed. (You can see this yourself on the "Checks" tab here on Github.) I am sufficiently removed from the Java ecosystem to not immediately know how to fix this -- it obviously works on the current master branch. Do you have any ideas what could be causing this?

**Comment by nanfangfanqie** [comment]
@jeremybmerrill: Sorry i didn't check it, i fix it in the latest commit, just need exclude junit-jupiter from pdfbox, we can re-run the CI.

**Comment by jeremybmerrill** [comment]
Hi @nanfangfanqie Thank you for the update. Now the tests run. However, some of them fail due to out-of-memory or heap space, and some of them fail due to an issue with font comparison. Do you see these failures too? If so, are you able to address them?

**Comment by nanfangfanqie** [comment]
Hi @jeremybmerrill Regarding the two issues you mentioned, I solved them in the latest two commits and running the unit tests locally passed, sorry for not checking before.

**Comment by jeremybmerrill** [comment]
Yay! Thank you! The tests pass for me. I will take a deeper look soon, but this is looking very good. Thank you again for bearing with my requests and my rusty Java :)

**Comment by THausherr** [comment]
Commits are easier to evaluate if they haven't any formatting changes.

**Comment by nanfangfanqie** [comment]
This is my mistake. In fact most of the changes are related to how PDFs are loaded and how fonts are declared.

**Review by jeremybmerrill — APPROVED** [review]
This all looks good to me. Thanks very much @nanfangfanqie for bearing with the delays and various cleanup requests.

**Comment by blacktek** [comment]
Hello,
  any plan to merge this pull request? I notice pdfbox 3.0.2 was release too.

Tnx!

**Comment by jeremybmerrill** [comment]
@jazzido What do you think about merging? Tests pass. (And I guess re-uploading to Maven, I think you have the keys to that? I'm sure I don't.)

@blacktek thx for the reminder. Despite the name of the thread, this PR would upgrade us to 3.0.2.

**Comment by blacktek** [comment]
@jazzido (sorry for the OT question): is there a plan to release a new version of the package in the coming weeks? last release is 2 years old. Thank you :)

**Comment by THausherr** [comment]
if you do, please accept all the dependabot PRs and run the versions plugin, here's what I get:

  com.google.code.gson:gson ............................ 2.9.0 -> 2.11.0
  commons-cli:commons-cli ................................. 1.4 -> 1.8.0
  org.apache.commons:commons-csv ....................... 1.9.0 -> 1.11.0
  org.locationtech.jts:jts-core ....................... 1.18.1 -> 1.19.0
  org.sonatype.plugins:nexus-staging-maven-plugin .... 1.6.8 -> 1.7.0
  maven-javadoc-plugin ............................... 3.3.1 -> 3.3.2
  maven-compiler-plugin ............................. 3.8.1 -> 3.12.1
  maven-javadoc-plugin ............................... 3.3.1 -> 3.6.3
  maven-source-plugin ................................ 3.2.1 -> 3.3.1
  maven-compiler-plugin ............................. 3.8.1 -> 3.13.0
  maven-javadoc-plugin ............................... 3.3.1 -> 3.7.0

**Pull request merged**
