### PR TITLE
Pdfbox2.0

### PR DESCRIPTION
**Pull request by melisabok**

### CODE REVIEW

**Comment by jeremybmerrill** [comment]
Yayyy!

Jeremy B. Merrill

**Comment by jazzido** [comment]
_Yayy_ indeed!

I've been looking and playing with @melisabok's branch as she was working on it, and everything looks great. I'll review this PR in the coming days, merge to `tabulapdf/tabula-java@pdfbox2.0` and push a `SNAPSHOT` to Maven Central.

**Comment by jazzido** [comment]
Hey @melisabok, I was wondering if you could take a quick look at this branch. From a clean clone, I'm getting a bunch of failed tests. Not sure what is going on. As far as I remember, the tests were passing.

Thanks!

**Comment by jazzido** [comment]
@melisabok, additional datapoint: all test pass in *your* `pdfbox2.0` branch (which I think is the branch which you sent this PR from).

**Comment by melisabok** [comment]
@jazzido I did a clean clone of the branch: https://github.com/tabulapdf/tabula-java/tree/pdfbox2.0

And I'm getting this result:
```
Tests run: 183, Failures: 44, Errors: 16, Skipped: 0
```
screen shot 2017-03-24 at 2 22 02 pm

that was my start point of my branch.

**Comment by jazzido** [comment]
Apologies, @melisabok. This was a total brain fart on my part. 

I did not merge your PR into *our* `pdfbox2.0` so **of course** there were failing tests. I just did and all works perfectly.

Sorry!

**Pull request merged**
