### PR TITLE
Add assertions in testNaturalOrderOfRectangles

### PR DESCRIPTION
**Pull request by melisabok**

### CODE REVIEW

**Comment by melisabok** [comment]
@jazzido Please keep open the PR

**Comment by jazzido** [comment]
No idea what I was trying to do, to be honest. It is probably a test that I wrote for tracing it with the debugger. Should be safe to remove.

**Comment by melisabok** [comment]
Ok. I didn't remove the test I refactored. ```RECTANGLES_TEST_NATURAL_ORDER``` was to big to remove it. 

I added another assert in [TestSpreadsheetExtractor](https://github.com/melisabok/tabula-java/blob/feature/add-assertions/src/test/java/technology/tabula/TestSpreadsheetExtractor.java#L370) but I think the output is missing some numbers:

```
HARVEST,VARIATION,,,
"11/12
(a)",12/13,Percentage,Absolute,
"","May/2013     
(b)","Jun/2013      
(c)",(c/a),
"1.393,4","886,7","894,9","(35,8)","( 498,5)"
"93,9","100,6","100,2","6,7","6,3"
"82,1","86,3","86,2","5,0","4,1"
"11,8","14,3","14,0","18,6","2,2"
"2.426,7","2.389,7","2.396,0","(1,3)","( 30,7)"
"3.262,1","2.952,7","3.026,9","(7,2)","( 235,2)"
"1.241,4","1.122,6","1.122,9","(9,5)","( 118,5)"
"1.394,6","1.275,4","1.271,7","(8,8)","( 122,9)"
"626,1","554,7","632,3","1,0","6,3"
"74,5","60,4","68,9","(7,5)","( 5,6)"
"128,2","87,5","87,4","(31,8)","( 40,8)"
"15.178,1","15.686,2","15.817,4","4,2","639,3"
"7.558,5","6.879,2","6.864,7","(9,2)","( 693,8)"
"7.619,6","8.807,0","8.952,7","17,5","1.333,1"
"25.042,2","27.715,2","27.715,5","10,7","2.673,3"
"786,9","836,4","836,4","6,3",
"48.386,0","50.715,4","50.943,6","5,3",
"153,0","168,7","168,7","10,3","15,7"
"42,4","43,8","43,8","3,3","1,4"
"2,3","2,3","2,3",-,-
"88,4","102,8","102,8","16,3","14,4"
"2.166,2","1.895,4","1.895,4","(12,5)","( 270,8)"
"46,9","48,0","48,0","2,3",
"2.499,2","2.261,0","2.261,0","(9,5)",
"50.885,2","5 2.976,4","5 3.204,6","4,6",
```


screen shot 2015-10-23 at 6 10 56 pm

**Comment by jazzido** [comment]
I would've thought that the reason for that failure is that there are no bounding lines for the entire spreadsheet (ie, no vertical lines at the *edges*). But the last cell on the 4th-from-last column is extracted correctly, so I'm stumped.

Can you try growing the extracting area horizontally and see what happens?

**Comment by melisabok** [comment]
Nop, I'm increasing the 'right' parameter and the output is the same

```
        Page page = UtilsForTesting.getAreaFromPage("src/test/resources/technology/tabula/spreadsheet_no_bounding_frame.pdf", 1,
                140.25f,54.1875f,649.1875f,1542.9375f);
```

**Comment by melisabok** [comment]
@jazzido I'm getting all the missing values when the table is extracted through isTabular method. I don't what is doing when it is creating the ```minimalRegion``` page. I added a [print](https://github.com/melisabok/tabula-java/blob/feature/add-assertions/src/main/java/technology/tabula/extractors/SpreadsheetExtractionAlgorithm.java#L225) of the JSON and you can check that it is completed.

**Pull request closed without merging**
