### PR TITLE
first stab at an RTL solution

### PR DESCRIPTION
**Pull request by jeremybmerrill**
a partial solution to #66.

In the most basic case, we reverse majority-RTL TextChunks.

We still get the wrong output in the 

1. mixed-directionality cases, ‫قطط‬ ‫‪47‬‬ ‫عندي‬ says "I have 47 cats" but Tabula outputs "I have 74 cats" because it reverses the whole string into logical order.
2. the laam-alif ligature is turned into just laam. This may be PDFBox related, because I traced it to here: https://github.com/tabulapdf/tabula-java/blob/master/src/main/java/technology/tabula/ObjectExtractor.java#L313-L314

Given those two problems, I think this is about an 80% solution and is better than nothing, so worth merging. Thoughts?

### CODE REVIEW

**Comment by mtigas** [comment]
+1 for merging. Seems like it gets us to where PDFBox is, or quite close. And doesn't seem to have any regressions on other bits, though let me fix the CI and see where how those tests go compared to master.

**Comment by jazzido** [comment]
Re: CI failure — looks like the build process wants to sign the .jar with my private GPG key (that I use for publishing to Maven central). I'm in thesis crunch time, so can't take care of that, but feel free to fix.

Thanks, guys! :metal:

**Comment by mtigas** [comment]
@jazzido `-Dgpg.skip=true` :tada: https://github.com/tabulapdf/tabula-java/commit/92e8d8215ef20fcf3cb660526407414aa5594c09

Think it’s failing on some timeouts now, getting killed on `eu-018.pdf` or `eu-019.pdf`. oh well.

**Comment by jazzido** [comment]
Yeah, the table detection tests are quite CPU heavy :(

**Comment by mtigas** [comment]
:tada: ddd249b545401dbbd60ffef3d747b2edfb46b5ab fixed the CI.

Doesn't look like this PR changed anything, test-wise. Identical conclusion to TestTableDetection:
```
==== CUMULATIVE TEST STATISTICS ====
51 out of 67 currently passing
140 out of 156 expected tables detected
30 tables incorrectly detected
```

So I’ll merge this in.

**Comment by jazzido** [comment]
Thanks a lot, @mtigas ! We missed you :)

**Comment by jeremybmerrill** [comment]
@mtigas @jazzido Can we re-merge this branch? I added some commits that handle bidi cells.

It's still not perfect:

- haven't dealt with table-level ordering like we talked about in the issue
- laam-alif ligature still isn't handled, but that's a PDFBox issue
- diacritics aren't handled; this also might be PDFBox, I haven't looked into it

**Pull request merged**
