### PR TITLE
[Monster PR] Upgrade to PDFBox 2.0

### PR DESCRIPTION
**Pull request by jazzido**
Now that @melisabok 's fantastic work has been merged to a branch, it's time to review it and finally merge it to `master`.

I plan to merge and cut a new `tabula-java` release within the next few days. In the mean time, feel free to comment, test and play with it.

### CODE REVIEW

**Comment by jazzido** [comment]
Those of you that have expressed interest in this (@gudipatiharitha, @subhashbylaiah, @beng06, @kapil-mangtani, @chezou), we're close to merging this to `master`. We'd love some feedback before we do so.

**Comment by chezou** [comment]
Thanks for your great work @melisabok  ! All tests in [tabula-py](https://github.com/chezou/tabula-py) have passed with this code. I also confirmed #114 is resolved :)

**Comment by jazzido** [comment]
Merged to `master` and updated version number to `1.0.0-SNAPSHOT`.

**Comment by jeremybmerrill** [comment]
Awesome, super exciting work. 

FYI, I made a couple of tiny tweaks to the tabula gui to support PDFBox 2.0 and the current tabula-java master branch. https://github.com/tabulapdf/tabula/tree/pdfbox2 A *basic* test of the GUI works fine with these tweaks (and I imagine the rest does, I just haven't checked).

I don't want to merge them into Tabula's master until we're ready to do a release of tabula-java, but, just FYI, that's there in case you're experimenting with the GUI.

It's worth considering adding a `pageCount` method to ObjectExtractor in Java. It would just be cleaner than the way I did it in Ruby and users of the Java APIs and other language bindings will have a good reason to use it (without having to figure out what's going on with `PDDocument`.

**Comment by jazzido** [comment]
Thanks for that. One additional thing that we should do before merging your
branch to master is replacing the current JPedal renderer with one that
used pdfbox (it renders PDFs perfectly now). I implemented one in
http://GitHub.com/tabulapdf/tabula-web-java (we would just need to Port it
to ruby)

**Comment by jeremybmerrill** [comment]
@jazzido Cool, I can handle htat

**Pull request merged**
