### PR TITLE
 Move tables serialization to the writers

### PR DESCRIPTION
**Pull request by melisabok**
- Move tables serialization to the writers
- Fix writeTables call, it was being called in each iteration
- Add writer tests json asserts, load from file

### CODE REVIEW

**Comment by melisabok** [comment]
Please review the code. I made some changes in the writers and I don't know if it is correct. 
I added 3 json files in the resources folder to test the serialization

**Comment by jazzido** [comment]
Thanks @melisabok, the PR looks great.

I think we should always serialize to a JSON array, even if we're extracting a single table. Can you add that to your branch? (I should have made that clearer before, sorry :( )

**Comment by melisabok** [comment]
@jazzido I think it always returns a JSON array. CommandLineApp only calls to:
```
write(Appendable out, List<Table> tables)
```

I left the other method in the Writer interface just in case, but I can remove it

**Comment by jazzido** [comment]
You're right, my bad. Merging and closing. Thanks again!

**Pull request merged**
