### PR TITLE
implement cell spanning

### PR DESCRIPTION
**Pull request by firegnome**
The changes are implemented like proposed in this comment without the markCellSpan option for CSV:

https://github.com/tabulapdf/tabula/issues/744#issuecomment-337388575

Changes:
CSVWriter:
- if the option **fillSpanCells** is set on the table, the writer will fill every cell that belongs to a span group

JSONWriter:
- always adds the property spanGroupId. If the field belongs to a span group it is > 0 otherwise its 0.
- if the option **fillSpanCells** is set on the table, the writer will fill every cell that belongs to a span 

I know it's always bad to edit the tests but it was necessary for these changes. Please have a look at them and let me know what you think.

### CODE REVIEW

**Comment by iWhacko** [comment]
In my opinion good code practices have indexes start at 0. (for i=0; I< x; i++) Arrays always start at 0.
So groupId should be -1 if not defined.

**Comment by firegnome** [comment]
@iWhacko 
This sounds reasonable, I will wait for other feedbacks and the implement this!

**Comment by jeremybmerrill** [comment]
Admittedly having not looked at the code, how does this relate to how cell spanning was implemented in tabula-extractor?

**Comment by firegnome** [comment]
Hey @jeremybmerrill
I think the screenshots i posted on this comment https://github.com/tabulapdf/tabula/issues/744#issuecomment-337388575 describe best what I‘ve changed. Look at the screenshot *actual behavior* and *new default behavior*. If you have more time you could look at the new test I‘ve added.

**Pull request closed without merging**
