### PR TITLE
Nurminen table detection

### PR DESCRIPTION
**Pull request by mcharters**
This branch implements a more sophisticated table detection algorithm based off Anssi Nurminen's masters thesis (more or less) which can be found here: http://dspace.cc.tut.fi/dpub/bitstream/handle/123456789/21520/Nurminen.pdf?sequence=3

With this algorithm, 49 of the 67 ground truth table detection tests pass. The remaining failures are mostly either tricky tables or false positives (which I'm guessing are more useful to tabula than not finding anything).

Note that this branch is based off mcharters:add-table-detection-tests, so it's got some extra changes in there.

### CODE REVIEW

**Comment by jazzido** [comment]
Hi @mcharters, thanks again for your hard work. 51 of 67 (~75%!) is an impressive number for the table detection method you implemented, so kudos for that.

That said, before merging your PR into `master`, I'd love to address the code duplication introduced by `NurminenDetectionAlgorithm`. In particular there are some methods that were already implemented in the `Ruling` class:

  - `NurminenDetectionAlgorithm.findRectangles` is almost identical to `SpreadsheetExtractionAlgorithm.findCells`
  - `NurminenDetectionAlgorithm.getTableAreasFromCells` looks *very* similar to `SpreadsheetExtractionAlgorithm.findSpreadsheetsFromCells`
  - `NurminenDetectionAlgorithm.getCrossingPoints` is identical to `Ruling.findIntersections`
  - `NurminenDetectionAlgorithm.merge{Horizontal,Vertical}Edges` are similar to `Ruling.collapseOrientedRulings`

This is, of course, reasonable since we both drew upon Nurminen's work. Here are a few refactoring ideas I'd like to suggest:

  - Move the rasterizing of a page to a separate class, or to a new method in the `Page` class (for this, the Page class will need to store a reference to the corresponding `PDPage` object)
  - Make the line-finding methods return instances of `Ruling` instead of `Line2D`. That way, we can use the existing methods.

Let me know what you think, and thanks again!

**Comment by mcharters** [comment]
Cool - I will take a look. I knew that I was probably duplicating some stuff, but I didn't want to step on any toes. I'll do some refactoring/retesting and let you know when I'm done.

**Comment by jazzido** [comment]
I've [just commited](47b8527993543bebde264bcfdc23ecffe50c227a) a change to `Page`: it'll now have a reference to the underlying `PDPage` instance. It can be used in `NurminenDetectionAlgorithm` instead of reopening the file for rendering.

**Comment by mcharters** [comment]
Thanks! I'm not convinced that the code for getting the rulings from the image raster should live in the Page class - right now the Page is a container for rulings created by the object extractor. and maybe it makes sense to keep it like that? I don't know that analyzing the page should change the rulings that the object extractor sets? I don't want to mess up any other uses of the page rulings.

**Comment by jazzido** [comment]
> […]I'm not convinced that the code for getting the rulings from the image raster should live in the Page class

Sure, it should not. I added that reference to the `PDPage` instance so you don't have to reopen the document in your detector implementation. So now, the second argument to the `detect` method can be removed:

```java
public List<Rectangle> detect(Page page) { 
  // ...
  BufferedImage image = page.getPDPage().convertToImage(BufferedImage.TYPE_BYTE_GRAY, 144);
// ...
}
```

Does this make sense?

**Comment by mcharters** [comment]
Yup, totally.

Sorry, my comment was more referring to "Move the rasterizing of a page to a separate class, or to a new method in the Page class".

**Comment by mcharters** [comment]
OK, I was able to reuse `Ruling.collapseOrientedRulings` and `SpreadsheetExtractionAlgorithm.findCells` (which also let me get rid of my duplicate crossing point algorithm).

I'm still using my own `getTableAreasFromCells` method because I allow cells that are a small distance apart to be part of the same table (this cuts down on a few failures in the ground truth data). I'll keep it that way unless we should be doing that for the SpreadsheetExtractionAlgorithm as well?

**Comment by jazzido** [comment]
> OK, I was able to reuse Ruling.collapseOrientedRulings and SpreadsheetExtractionAlgorithm.findCells (which also let me get rid of my duplicate crossing point algorithm).

Awesome. Deleting huge chunks of code always makes me happy :)

> I'm still using my own getTableAreasFromCells method because I allow cells that are a small distance apart to be part of the same table (this cuts down on a few failures in the ground truth data). I'll keep it that way unless we should be doing that for the SpreadsheetExtractionAlgorithm as well?

Can you point me to the difference between your method and ours? If incorporating that change to `SpreadsheetExtractionAlgorithm.findSpreadsheetsFromCells` doesn't break our tests, we can get rid of one of them.

**Comment by mcharters** [comment]
OK, from looking closer at the `findSpreadhseetsFromCells` method it's much more sophisticated than mine. I'm just taking each cell (from top-left-most to bottom-right-most) and checking cell by cell to see if the next cell shares any corners with any cells in my current "table" and that's where I add the distance threshold - cells can be a little bit away and be considered part of the table.

I think to modify the `findSpreadhseetsFromCells` algorithm to be similar it would involve writing more code to snap all the points in the `pointSet` to some sort of grid before finding the horizontal and vertical lines - unless I'm missing something. This seems like it would be tricky to me?

**Comment by jazzido** [comment]
Small refactor suggestion:

We already have a *top-leftmost* `Point2D` comparator [here](https://github.com/tabulapdf/tabula-java/blob/master/src/main/java/technology/tabula/ObjectExtractor.java#L407) — We could move it to `Utils` and reuse it from `NurminenDetectionAlgorithm`.

**Comment by jazzido** [comment]
> OK, from looking closer at the findSpreadhseetsFromCells method it's much more sophisticated than mine […]

Right. Let's keep yours for now, then.

**Comment by jazzido** [comment]
I think it now looks good for merging into `master`. Last request: can you set up the tests so the ones that pass at this point are ran by default in the test suite? That way we make sure not to introduce regressions in the detector.

Thanks!

**Comment by mcharters** [comment]
@jazzido it looks like the tests are failing because PDFBox is logging too much. Do you know if there's an easy way to temporarily turn off logging or will I have to add log4j as a dependency and do it programatically for the tests?

**Comment by mcharters** [comment]
Well that's fun. I guess there must be enough of a difference between my flavour of java and travis' flavour that there are failures in the integration tests that don't appear locally.

I'll try to think of some clever way around this but suggestions are welcome!

**Comment by mcharters** [comment]
OK I can reproduce the failures in an old vagrant box. I'll dig into the failures.

**Comment by mcharters** [comment]
Phew! OK, by adding a little more "fuzziness" to a couple parts of the algorithm I was able to align the tests over a bunch of platforms (windows, os x & ubuntu). Might be ready to go now?

**Comment by jazzido** [comment]
Merged! Thanks a lot @mcharters. Your PR is the biggest contribution we received in the history of Tabula.

**Comment by jazzido** [comment]
I've just integrated the new detector in Tabula (web). This is **awesome**

screen shot 2016-02-02 at 1 55 07 pm

(@jeremybmerrill , @mtigas, take a look :))

**Pull request merged**
