### PR TITLE
ignore area if the page has no text. closes #130

### LINKED ISSUE #130: Exception raised when specifying area with pdf that has spare blank pages
`java -jar ./tools/tabula-0.9.1-jar-with-dependencies.jar pdf_with_blank_page.pdf --pages all --spreadsheet -u -a 0,0,864.567,1105.51`

Exception in thread "main" java.util.NoSuchElementException
	at java.util.ArrayList$Itr.next(ArrayList.java:854)
	at java.util.Collections.min(Collections.java:635)
	at technology.tabula.Page.getArea(Page.java:68)
	at technology.tabula.CommandLineApp.extractFile(CommandLineApp.java:163)
	at technology.tabula.CommandLineApp.extractFileInto(CommandLineApp.java:138)
	at technology.tabula.CommandLineApp.extractFileTables(CommandLineApp.java:128)
	at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:104)
	at technology.tabula.CommandLineApp.main(CommandLineApp.java:74)

Example doc:
[pdf_with_blank_page.pdf](https://github.com/tabulapdf/tabula-java/files/657616/pdf_with_blank_page.pdf)

Will send a one liner PR to solve it

### PR DESCRIPTION
**Pull request by jjelosua**
Basically ignore the page with area restrictions creation when there's no text elements on the page
https://github.com/jjelosua/tabula-java/blob/master/src/main/java/technology/tabula/Page.java#L56

### CODE REVIEW

**Comment by jazzido** [comment]
Thanks Juan! I know I'm being a PITA, but could re-submit your PR without so many whitespace changes? I'd love to keep the change history as clean as possible so it's easy to review.

Thanks!

**Comment by jeremybmerrill** [comment]
this will close #105, #107, #77 as well. Thanks @jjelosua! Also probably https://github.com/tabulapdf/tabula/issues/573

**Comment by jjelosua** [comment]
@jazzido Done

**Comment by jazzido** [comment]
You rock, @jjelosua. Gracias!

**Comment by jeremybmerrill** [comment]
@jjelosua @jazzido: Please see the error reported by @blomdahldaniel here: https://github.com/tabulapdf/tabula-java/issues/107

I think this PR introduces a new bug. Perhaps the early return (if there are no texts) should be a new Page object with no texts and with the rulings uncropped (it's [lines 68-78](https://github.com/jjelosua/tabula-java/blob/dfd5f2f2ebd27adf8afc73173d4aefb9c92e6451/src/main/java/technology/tabula/Page.java#L68-L78) that cause the original problem).

**Pull request merged**
