### PR TITLE
Refactor data clumps code-smell in Page class

### PR DESCRIPTION
**Pull request by GustavAT**
Introduce builder pattern for the Page class

### CODE REVIEW

**Comment by GustavAT** [comment]
Wrong repository

**Comment by jazzido** [comment]
LOL, no worries. 

I like that change anyways. Would love to get that PR merged as well :)

**Comment by jazzido** [comment]
@W3D3 @GustavAT BTW, I like some of the changes that you guys are pushing to your branch. Do you mind if I cherry-pick some of them?

**Comment by GustavAT** [comment]
@jazzido Please feel free to do - it's open source anyway :)

**Comment by W3D3** [comment]
@jazzido Yeah I agree, take whatever you like :+1:

**Pull request merged**
