### PR TITLE
Some test class/case updates

### PR DESCRIPTION
**Pull request by tuneribaba**
Got it!

Note: Not all the test cases are best and can be improved for better test quality and coverage.

It was fun working on you repo!

Cheers,
Tunde

### CODE REVIEW

**Comment by jeremybmerrill** [comment]
Whoa, this is awesome. Thanks @tuneribaba!

**Comment by tuneribaba** [comment]
Hi Manuel,

I noticed the PR has not yet been accepted. Was there something wrong with merging in the changes?

Cheers,
Tunde

**Comment by jazzido** [comment]
Hi Tunde,

The PR looks good. I'll take a look and merge it in a couple weeks, I'm under a very tight deadline at the moment.

Thanks again and sorry for the delay!

M

**Comment by jazzido** [comment]
Hi @tuneribaba,

There's one failure in the tests that you added: https://travis-ci.org/tabulapdf/tabula-java/jobs/122879444#L1357

Looks like a simple thing. If you have the chance to fix that, and push to this branch, I can merge your PR right away.

Thanks!

**Comment by tuneribaba** [comment]
Ooops sorry for the delay. Made the change.

Thanks,
Tunde

**Comment by jazzido** [comment]
Merged. Thanks again!

**Comment by jazzido** [comment]
Hey @tuneribaba, if you don't mind me asking: I noticed that there was a PDF report about the work you did on Tabula's codebase. Was it a class project?

**Comment by tuneribaba** [comment]
Hey @jazzido. Yes it was a class assignment in a graduate course at UBC.

**Pull request merged**
