### PR TITLE
Add  right and bottom of area to JSON output

### PR DESCRIPTION
**Pull request by laigor**

### CODE REVIEW

**Comment by jazzido** [comment]
Hi @laigor,

Thanks for your contribution! I noticed that the tests for the JSON writer are failing after your commit. Would you mind updating this PR with the fixes?

Thanks!

**Comment by laigor** [comment]
I saw that the tests do not pass, but I do not know how to fix them.

**Comment by jeremybmerrill** [comment]
I haven't checked, but if I recall correctly, the test is just checking that the output hasn't changed. Since this adds the `right` and `bottom`... the output has changed. It's presumably just a matter of changing the file the tests check against to the current output...

**Comment by jazzido** [comment]
Tests modified, and PR merged. Thanks again @laigor !

**Pull request merged**
