### PR TITLE
New character merging heuristics

### PR DESCRIPTION
**Pull request by jazzido**
As per these commits:
- tabulapdf/tabula-extractor@0743e96
- tabulapdf/tabula-extractor@9e69136
- tabulapdf/tabula-extractor@c7fd88c
- tabulapdf/tabula-extractor@da2ab4f
- tabulapdf/tabula-extractor@0b47c4f

### CODE REVIEW

**Comment by jazzido** [comment]
Should we merge this one? This is the only failure:

```
testExtractColumnsCorrectly3(technology.tabula.TestBasicExtractor)  Time elapsed: 0.571 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<AARON ,[ JOSHUA, ]N> but was:<AARON ,[JOSHUA,]N>
```

Looks pretty harmless.

**Comment by jeremybmerrill** [comment]
Yeah. We were wrong either way, so what's another missing space?

**Comment by jazzido** [comment]
Hey @jeremybmerrill — We don't need this anymore, do we?

**Comment by jeremybmerrill** [comment]
@jazzido not afaik

**Pull request closed without merging**
